# Generated by Django 5.0.6 on 2024-05-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authlogin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='customerId',
            field=models.IntegerField(unique=True),
        ),
    ]
