# Generated by Django 5.0.6 on 2024-05-22 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authlogin', '0002_alter_user_customerid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
        migrations.RemoveField(
            model_name='user',
            name='isSuperuser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='state',
        ),
        migrations.RemoveField(
            model_name='user',
            name='zip',
        ),
    ]
